name: pismo-challenge
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=pismo
      - MYSQL_PASSWORD=pismo
      - MYSQL_DATABASE=pismo-challenge
    ports:
      - 127.0.0.1:3308:3306
volumes:
  mysql_data:
